export const SECONDS_PER_MINUTE = 60;
export const MINUTES_PER_HOUR = 60;
export const HOURS_PER_DAY = 24;
export const DAYS_PER_MONTH = 30;

export const ACCESS_TOKEN_EXPIRY = SECONDS_PER_MINUTE;
export const REFRESH_TOKEN_EXPIRY =
  DAYS_PER_MONTH * HOURS_PER_DAY * MINUTES_PER_HOUR * SECONDS_PER_MINUTE;
