import "@repo/ui/styles.css";
import "./globals.css";

import { Toaster } from "@repo/ui/sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="light" lang="en">
      <body className={inter.className}>{children}</body>
      <Toaster />
    </html>
  );
}
